"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-Uniswap-AgenticFinance',
 'project_name': 'YieldGuard Liquidity Rail',
 'track': 'Uniswap Agentic Finance',
 'pitch': 'An agentic liquidity rail that only deploys approved yield into swaps, '
          'hooks-aware liquidity moves, and cross-chain settlement with dry-run '
          'receipts.',
 'idea_titles': ['Autonomous Cross-Chain Arbitrage Swarm',
                 'Hooks-Aware Yield Rebalancer',
                 'Proof-of-Liquidity Treasury Agent'],
 'architecture_summary': 'Python agents watch Uniswap and partner signals, assemble '
                         'bounded rebalance plans, and record dry-run hashes before '
                         'any spend. A policy contract enforces targets, caps, and '
                         'cooldowns while demo scripts outline how real swaps, bridge '
                         'legs, and settlement receipts will be attached once API keys '
                         'and wallets are loaded.',
 'overlap_targets': ['Lido stETH Treasury',
                     'Bankr Gateway',
                     'Filecoin',
                     'Celo',
                     'MetaMask Delegations',
                     'PayWithLocus',
                     'Bond.credit'],
 'primary_contract_name': 'UniswapExecutionGuard',
 'primary_python_module': 'uniswap_agent',
 'category': 'trading',
 'daily_budget_usd': 126,
 'per_action_budget_usd': 31,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'market_route',
                       'description': 'Quotes, liquidity windows, and execution '
                                      'candidates.'},
                      {'name': 'risk_policy',
                       'description': 'Caps, cooldowns, and verification gates.'},
                      {'name': 'execution_bundle',
                       'description': 'Prepared route and settlement metadata.'},
                      {'name': 'receipts',
                       'description': 'Trade digests, proofs, and reporting notes.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for UniswapExecutionGuard.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'uniswap_agent.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'Uniswap',
               'docs_url': 'https://developers.uniswap.org/',
               'env_vars': ['UNISWAP_API_KEY', 'UNISWAP_QUOTE_URL'],
               'endpoint_env': 'UNISWAP_QUOTE_URL',
               'action_kind': 'rest_json',
               'purpose': 'Quote swaps and bounded liquidity moves.'},
              {'name': 'Lido',
               'docs_url': 'https://docs.lido.fi/',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Route staking yield through guarded treasury actions.'},
              {'name': 'Bankr Gateway',
               'docs_url': 'https://bankr.bot/',
               'env_vars': ['BANKR_API_KEY',
                            'BANKR_CHAT_COMPLETIONS_URL',
                            'BANKR_MODEL'],
               'endpoint_env': 'BANKR_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Route inference through cost-aware model selection.'},
              {'name': 'Filecoin',
               'docs_url': 'https://docs.filecoin.cloud/',
               'env_vars': ['FILECOIN_API_TOKEN', 'FILECOIN_UPLOAD_URL'],
               'endpoint_env': 'FILECOIN_UPLOAD_URL',
               'action_kind': 'file_upload',
               'purpose': 'Persist proofs, logs, and evidence bundles offchain.'},
              {'name': 'Celo',
               'docs_url': 'https://docs.celo.org/',
               'env_vars': ['CELO_RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Settle stablecoin-native transfers on Celo rails.'},
              {'name': 'MetaMask Delegations',
               'docs_url': 'https://docs.metamask.io/delegation-toolkit/',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Enforce delegation scopes, expiries, and intent envelopes.'},
              {'name': 'PayWithLocus',
               'docs_url': 'https://docs.locus.finance/',
               'env_vars': ['LOCUS_API_KEY', 'LOCUS_PAYMENT_URL'],
               'endpoint_env': 'LOCUS_PAYMENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Create bounded subaccounts and controlled spend flows.'},
              {'name': 'Bond.credit',
               'docs_url': 'https://bond.credit/',
               'env_vars': ['GMX_ORDER_URL', 'BOND_CREDIT_PROFILE_URL'],
               'endpoint_env': 'GMX_ORDER_URL',
               'action_kind': 'rest_json',
               'purpose': 'Journal bounded trades and credit-profile updates.'}],
 'actions': [{'id': 'uniswap_quote_route',
              'target': 'uniswap',
              'purpose': 'Use Uniswap for a bounded action in this repo.',
              'partner': 'Uniswap',
              'action_kind': 'rest_json',
              'max_amount_usd': 220,
              'priority': 100,
              'sensitivity': 'medium',
              'notes': ['Call Uniswap only after a dry-run artifact exists.',
                        'Use https://developers.uniswap.org/ for credential setup.']},
             {'id': 'lido_yield_route',
              'target': 'lido',
              'purpose': 'Use Lido for a bounded action in this repo.',
              'partner': 'Lido',
              'action_kind': 'contract_call',
              'max_amount_usd': 200,
              'priority': 95,
              'sensitivity': 'medium',
              'notes': ['Call Lido only after a dry-run artifact exists.',
                        'Use https://docs.lido.fi/ for credential setup.']},
             {'id': 'bankr_gateway_compute_route',
              'target': 'bankr_gateway',
              'purpose': 'Use Bankr Gateway for a bounded action in this repo.',
              'partner': 'Bankr Gateway',
              'action_kind': 'rest_json',
              'max_amount_usd': 10,
              'priority': 90,
              'sensitivity': 'high',
              'notes': ['Call Bankr Gateway only after a dry-run artifact exists.',
                        'Use https://bankr.bot/ for credential setup.']},
             {'id': 'filecoin_proof_store',
              'target': 'filecoin',
              'purpose': 'Use Filecoin for a bounded action in this repo.',
              'partner': 'Filecoin',
              'action_kind': 'file_upload',
              'max_amount_usd': 20,
              'priority': 85,
              'sensitivity': 'medium',
              'notes': ['Call Filecoin only after a dry-run artifact exists.',
                        'Use https://docs.filecoin.cloud/ for credential setup.']},
             {'id': 'celo_payment_settle',
              'target': 'celo',
              'purpose': 'Use Celo for a bounded action in this repo.',
              'partner': 'Celo',
              'action_kind': 'contract_call',
              'max_amount_usd': 150,
              'priority': 80,
              'sensitivity': 'low',
              'notes': ['Call Celo only after a dry-run artifact exists.',
                        'Use https://docs.celo.org/ for credential setup.']},
             {'id': 'metamask_delegations_delegate_scope',
              'target': 'metamask_delegations',
              'purpose': 'Use MetaMask Delegations for a bounded action in this repo.',
              'partner': 'MetaMask Delegations',
              'action_kind': 'contract_call',
              'max_amount_usd': 2,
              'priority': 75,
              'sensitivity': 'high',
              'notes': ['Call MetaMask Delegations only after a dry-run artifact '
                        'exists.',
                        'Use https://docs.metamask.io/delegation-toolkit/ for '
                        'credential setup.']},
             {'id': 'paywithlocus_subaccount_pay',
              'target': 'paywithlocus',
              'purpose': 'Use PayWithLocus for a bounded action in this repo.',
              'partner': 'PayWithLocus',
              'action_kind': 'rest_json',
              'max_amount_usd': 120,
              'priority': 70,
              'sensitivity': 'medium',
              'notes': ['Call PayWithLocus only after a dry-run artifact exists.',
                        'Use https://docs.locus.finance/ for credential setup.']},
             {'id': 'bond_credit_credit_trade',
              'target': 'bond_credit',
              'purpose': 'Use Bond.credit for a bounded action in this repo.',
              'partner': 'Bond.credit',
              'action_kind': 'rest_json',
              'max_amount_usd': 90,
              'priority': 65,
              'sensitivity': 'high',
              'notes': ['Call Bond.credit only after a dry-run artifact exists.',
                        'Use https://bond.credit/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
